### ISSUE TITLE
Mod conflict

### ISSUE THREAD

**Issue by Sci648** [daipenger/Sound-Physics#14]
MC version 1.11.2 Forge 12.20.1.2388
First off thank you so much for working on the mod. secondly found out it crashes when sounds from the Animania mod plays. Not sure if this is known or not. I can attach a crash report if you like here is the little exerpt that leads me to believe it is with animania.

net.minecraft.server.MinecraftServer	Server thread	error	Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.sonicether.soundphysics.SoundPhysics.calculateEntitySoundOffset(SoundPhysics.java:183)
	at net.minecraft.entity.Entity.func_184185_a(Entity.java:1066)
	at com.animania.common.entities.amphibians.EntityAmphibian.func_70637_d(EntityAmphibian.java:120)
	at com.animania.common.entities.amphibians.EntityAmphibian.startJumping(EntityAmphibian.java:124)
	at com.animania.common.entities.amphibians.EntityAmphibian.func_70619_bc(EntityAmphibian.java:153)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:901)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:680)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:39)
	at com.animania.common.entities.amphibians.EntityAmphibian.func_70636_d(EntityAmphibian.java:207)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	... 4 more

**Comment by daipenger** [comment]
https://github.com/capnkirok/animania/issues/256
Fixed on their side.
